In [36]:
import pandas as pd

cid = ['cid-0001', 'cid-0002', 'cid-0003', 'cid-0004', 'cid-0005'] # elements of lists are seperated by comma

## Let's print the list to see if this works
print("Customer ID:",cid)

Customer ID: ['cid-0001', 'cid-0002', 'cid-0003', 'cid-0004', 'cid-0005']

In [37]:
credit_score = [650, 723, 581, 462, 773]   # list for storing credit score
age_of_customer = [25, 28, 38, 41, 62]     # list for storing age of the customer
debt_status = ['no-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt']  # list to store the debt status
no_of_existing_credit_cards = [3, 2, 4, 1, 2] # list to store the number of existing credit cards

## Let's print the list to see if this works
print("Credit Score:",credit_score)
print("Age of Customer:",age_of_customer)       
print("Debt Status:",debt_status)
print("Number of existing Credit Cards:",no_of_existing_credit_cards)

Credit Score: [650, 723, 581, 462, 773]
Age of Customer: [25, 28, 38, 41, 62]
Debt Status: ['no-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt']
Number of existing Credit Cards: [3, 2, 4, 1, 2]

In [38]:
## To get data of cid-0002 we need to first find the index of the same.
pos = cid.index('cid-0002') # index() is used to fetch the index of the value mentioned
print(pos)

1

In [39]:
## Now that we know the index, let's call the value stored at the index for all the lists.
print(cid[pos])
print(credit_score[pos])
print(age_of_customer[pos])
print(debt_status[pos])
print(no_of_existing_credit_cards[pos])

cid-0002
723
28
no-debt
2

In [40]:
#Let's first find the index of cid-0001
pos = cid.index('cid-0001')     #saving the index of cid-001 in pos

In [41]:
#Let's assign the updated status
debt_status[pos] = 'in-debt'    #updating debt_status for the index variable pos

In [42]:
debt_status

['in-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt']

In [43]:
# Let's first create the list prec_on_time
# Assume that the below random numbers is the on-time payment percentage
prec_on_time = [0.62, 0.78, 0.20, 0.32, 0.85]

In [44]:
if prec_on_time[0] > 0.7:
    credit_score[0] = round(credit_score[0] * 1.02)   #adding 2% will be equal to 1+0.02 = 1.02
    print('Credit Score updated for cid-0001')
else:
    print('Credit Score is same for cid-0001')

if prec_on_time[1]>0.7:
    credit_score[1] = round(credit_score[1] * 1.02)
    print('Credit Score updated for cid-0002')
else:
    print('Credit Score is same for cid-0002')

if prec_on_time[2]>0.7:
    credit_score[2] = round(credit_score[2] * 1.02)
    print('Credit Score updated for cid-0003')
else:
    print('Credit Score is same for cid-0003')

if prec_on_time[3]>0.7:
    credit_score[3] = round(credit_score[3] * 1.02)
    print('Credit Score updated for cid-0004')
else:
    print('Credit Score is same for cid-0004')

if prec_on_time[4]>0.7:
    credit_score[4] = round(credit_score[4] * 1.02)
    print('Credit Score updated for cid-0005')
else:
    print('Credit Score is same for cid-0005')

Credit Score is same for cid-0001
Credit Score updated for cid-0002
Credit Score is same for cid-0003
Credit Score is same for cid-0004
Credit Score updated for cid-0005

In [45]:
#Now, since we want to increase the credit score by 2%, 
# we will first check if the prec_on_time value is greater than 0.7. 
# We can do this with the help of conditional statements and for loop.

for i in range(len(prec_on_time)):
    if prec_on_time[i]>0.7:
        credit_score[i] = round(credit_score[i] * 1.02) #adding 2% will be equal to 1+0.02 = 1.02
        print('Credit Score updated for',cid[i])
    else:
        print('Credit Score is same for',cid[i])

Credit Score is same for cid-0001
Credit Score updated for cid-0002
Credit Score is same for cid-0003
Credit Score is same for cid-0004
Credit Score updated for cid-0005

In [46]:
credit_score
#Great we can see the credit score is updated for cid-0002 and cid-0005.
#  This worked since we had only 5 users but it will be very time consuming 
# and repetitive if we have many users. We should find a better way of coding 
# that allows us to iterate through the list more easily.

[650, 752, 581, 462, 804]

In [47]:
#Let's say, we have to reduce the credit score for those users whose prec_on_time is less than 40% by 2%

for i in range(len(prec_on_time)):
    if prec_on_time[i]<0.4:
        credit_score[i] = round(credit_score[i] * 0.98)  #subtracting 2% will be equal to 1-0.02 = 0.98
        print('Credit Score updated for',cid[i])
    else:
        print('Credit Score is same for',cid[i])

Credit Score is same for cid-0001
Credit Score is same for cid-0002
Credit Score updated for cid-0003
Credit Score updated for cid-0004
Credit Score is same for cid-0005

In [48]:
#**Let's find out how many people have credit score greater than 700?**

# Initialize counter to increment the customer count
count = 0

for i in range(0,len(cid)):
    if credit_score[i]>700:
        count +=1 # Incrementing count counter by 1 when the credit score is greater than 700

print('Number of people having credit score greater than 700:',count)

Number of people having credit score greater than 700: 2

In [49]:
#**Can we check How many people have more than 2 credit cards?**

# Initialize counter to increment the customer count
count = 0

for i in range(0,len(cid)):
    if no_of_existing_credit_cards[i]>2:
        count +=1 # Incrementing count counter by 1 when number of credit cards are greater than 2
print('Number of people having more than 2 credit cards:',count)

Number of people having more than 2 credit cards: 2

In [50]:
#**Can we count how many people are in debt and how many are in not debt ?**

# Initialize counter to increment the customer count
count_in_debt = 0
count_not_in_debt = 0

for i in range(0,len(cid)):
    if debt_status[i]=='in-debt':
        count_in_debt +=1 # Incrementing count counter by 1 when the customer is in debt
    else:
        count_not_in_debt +=1 # Incrementing count counter by 1 when the customer is not in debt
print('Number of people in debt:',count_in_debt)
print('Number of people not in debt:',count_not_in_debt)

Number of people in debt: 2
Number of people not in debt: 3

In [51]:
#**Let's try to print all the information of customer whose customer id = cid-0002**

for i in range(len(cid)):
    if cid[i]=='cid-0002':
        print('Customer ID:',cid[i])
        print('Credit Score:',credit_score[i])
        print('Age of Customer:',age_of_customer[i])
        print('Debt Status:',debt_status[i])
        print('Number of existing Credit Cards:',no_of_existing_credit_cards[i])
        break
    else:
        continue

Customer ID: cid-0002
Credit Score: 752
Age of Customer: 28
Debt Status: no-debt
Number of existing Credit Cards: 2

In [52]:
#### **1.4 Modular way of updating data**
def customer_info(c_id): # def(keyword) is used to define a function followed by the function name and parameters
    for i in range(0,len(cid)): # setting up a for loop to iterate through all the customer id's
        if cid[i] == c_id:
            print('---------------------------------------------------------------------')
            print( 'Customer ID:',cid[i])
            print( 'Credit Score:',credit_score[i])
            print( 'Age of the Customer:',age_of_customer[i])
            print( 'Debt Status:',debt_status[i])
            print( 'Number of existing Credit Cards:',no_of_existing_credit_cards[i])

In [53]:
customer_info('cid-0001') # Calling the above defined function

---------------------------------------------------------------------
Customer ID: cid-0001
Credit Score: 650
Age of the Customer: 25
Debt Status: in-debt
Number of existing Credit Cards: 3

In [54]:
customer_info('cid-0003')

---------------------------------------------------------------------
Customer ID: cid-0003
Credit Score: 569
Age of the Customer: 38
Debt Status: no-debt
Number of existing Credit Cards: 4

In [55]:
#### **1.5 Combining all the data into a single data element**
# **What is a Dictionary?**
# >Dictionaries are used to store data values in key:value pairs.

# **What's so special about Dictionary?**
# >Dictionary items are ordered, changeable, and does not allow duplicates.

# **How to declare a Dictionary?**
# >Syntax for the dictionary is:
# > ```
#  dictionary = {'key1':value1,'key2':value2,...,'key_n':value_n}
# ```

In [56]:
# dictionary is created with key and value pairs
df1 = {
    'cust_id': cid,
    'cred_score': credit_score,
    'age': age_of_customer,
    'debt_status':debt_status,
    'curr_cred_cards':no_of_existing_credit_cards
}

In [57]:
df1

{'cust_id': ['cid-0001', 'cid-0002', 'cid-0003', 'cid-0004', 'cid-0005'],
 'cred_score': [650, 752, 569, 453, 804],
 'age': [25, 28, 38, 41, 62],
 'debt_status': ['in-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt'],
 'curr_cred_cards': [3, 2, 4, 1, 2]}

In [58]:
df1['cust_id'] # fetch all the values under the key 'cust_id'

['cid-0001', 'cid-0002', 'cid-0003', 'cid-0004', 'cid-0005']

In [59]:
df1['cust_id'][2] # to fetch the 3rd element in the list 'cust_id'

'cid-0003'

In [60]:
for key, value in df1.items():  # Iterating through all the keys of dictionary, with values index as constant
    print(key ,value[3])

cust_id cid-0004
cred_score 453
age 41
debt_status in-debt
curr_cred_cards 1

In [61]:
## **2.0 Getting data into a convenient structure**

In [62]:
# **What is the Pandas Library?**

# Pandas is an open-source Python Library providing high-performance 
# data manipulation and analysis tools using its powerful data structures. 
# It is fast, flexible, and expressive data structure designed to make working
#  with 'numerical' or 'categorical' data both easy and intuitive. 
# It aims to be the fundamental high-level building block for doing practical,
#  real world data analysis in Python.

# **Why do we use Pandas?**
# - Used for analyzing, cleaning, exploring, and manipulating data.

In [63]:
# import is used to call upon any library that is installed in the system.
import pandas as pd  # anything after 'as' will become an alias for the library name

In [64]:
# Dataframe can be created by using the function pd.Dataframe
df = pd.DataFrame(df1)
df

    cust_id  cred_score  age debt_status  curr_cred_cards
0  cid-0001         650   25     in-debt                3
1  cid-0002         752   28     no-debt                2
2  cid-0003         569   38     no-debt                4
3  cid-0004         453   41     in-debt                1
4  cid-0005         804   62     no-debt                2

In [65]:
### **2.2 Accessing and analysing the data**

In [66]:
# let's print top 3 data entries
df.head(3) # without any value inside the brackets, it will print the top 5 entries of the data

    cust_id  cred_score  age debt_status  curr_cred_cards
0  cid-0001         650   25     in-debt                3
1  cid-0002         752   28     no-debt                2
2  cid-0003         569   38     no-debt                4

In [67]:
# Let's print the last 3 data entries
df.tail(3) # without any value inside the brackets, it will print the last 5 entries of the data

    cust_id  cred_score  age debt_status  curr_cred_cards
2  cid-0003         569   38     no-debt                4
3  cid-0004         453   41     in-debt                1
4  cid-0005         804   62     no-debt                2

In [68]:
# Let's create statistical summary
df.describe()

       cred_score        age  curr_cred_cards
count    5.000000   5.000000         5.000000
mean   645.600000  38.800000         2.400000
std    140.883995  14.584238         1.140175
min    453.000000  25.000000         1.000000
25%    569.000000  28.000000         2.000000
50%    650.000000  38.000000         2.000000
75%    752.000000  41.000000         3.000000
max    804.000000  62.000000         4.000000

In [69]:
df.shape

(5, 5)

In [70]:
# To get the information about the number of columns, rows datatype and memory usage we use info function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cust_id          5 non-null      object
 1   cred_score       5 non-null      int64
 2   age              5 non-null      int64
 3   debt_status      5 non-null      object
 4   curr_cred_cards  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes